---
title: "Final_Project_Part_3_C"
author: "Peng Yuan"
date: '2023-04-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Classification – iiiC) GLM Predictions
### 1. Load package, data and model
#### 1.1 Load package
```{r,1.1_solution}
library(tidyverse)
library(caret)
library(coefplot)
library(rstanarm)
library(splines)
```

#### 1.2 Load data
```{r,1.2_solution}
df_all <- readr::read_csv("paint_project_train_data.csv", col_names = TRUE)


df <- df_all %>%
  subset(select = c(R, G, B, Hue)) %>% 
  scale() %>% as.data.frame() %>%
  bind_cols(df_all %>% subset(select = c(Lightness, Saturation, outcome)))

dfiii <- df %>% 
  mutate(outcome = ifelse(outcome == 1, 'event', 'non_event'),
         outcome = factor(outcome, levels = c('event', 'non_event')))

dfiii %>% glimpse()
```

#### 1.3 Load model
```{r}
class_stan_glm_mod6 <- readr::read_rds("Model/class_stan_glm_mod6.rds")
class_stan_glm_mod8 <- readr::read_rds("Model/class_stan_glm_mod8.rds")
```


### Predict Model
#### 2.1 Build prediction model
```{r}
viz_grid <- expand.grid(R = median(dfiii$G),
                        G = seq(min(dfiii$R), max(dfiii$R), length.out = 25),
                        B = median(dfiii$B),
                        Lightness = "dark",
                        Saturation = "gray",
                        Hue = quantile(dfiii$Hue, 
                                           probs = c(0.05, 0.25, 0.5, 0.75, 0.95), 
                                           na.rm = TRUE),
                        KEEP.OUT.ATTRS = FALSE,
                        stringsAsFactors = FALSE) %>% 
  as.data.frame() %>% tibble::as_tibble()

viz_grid %>% glimpse()
```

#### 2.2 Draw predictive mean trend
**Model 6**
```{r}
posterior_predict(class_stan_glm_mod6, newdata = viz_grid) %>%
  as.data.frame() %>% tibble::as_tibble() %>%
  tibble::rowid_to_column("post_id") %>%
  tidyr::gather(key = "pred_id", value = "value", -post_id) %>%
  mutate_at(c("pred_id"), as.numeric) %>%
  group_by(pred_id) %>%
  summarise(num_post = n(),
            trend_avg = mean(value),
            trend_lwr = quantile(value, 0.05),
            trend_upr = quantile(value, 0.95)) %>%
  ungroup() %>%
  left_join(viz_grid %>% tibble::rowid_to_column("pred_id"),
            by = "pred_id") %>%
  ggplot(mapping = aes(x = G)) +
  geom_ribbon(mapping = aes(ymin = trend_lwr,
                            ymax = trend_upr,
                            group = Hue,
                            fill = as.factor(Hue)),
              alpha = 0.5) +
  geom_line(mapping = aes(y = trend_avg,
                          group = Hue,
                          color = as.factor(Hue)),
            size = 1.) +
  facet_wrap(~Hue, scales = 'fixed')+
  scale_fill_viridis_d("Hue") +
  scale_color_viridis_d("Hue") +
  labs(y = "mean trend") +
  theme_bw() +
  theme(legend.position = "top")

```



```{r}
posterior_predict(class_stan_glm_mod6, newdata = viz_grid) %>% 
  as.data.frame() %>% tibble::as_tibble() %>% 
  tibble::rowid_to_column("post_id") %>% 
  tidyr::gather(key = "pred_id", value = "value", -post_id) %>% 
  mutate_at(c("pred_id"), as.numeric) %>% 
  group_by(pred_id) %>% 
  summarise(y_avg = mean(value),
            y_lwr = quantile(value, 0.05),
            y_upr = quantile(value, 0.95)) %>% 
  ungroup() %>% 
  left_join(boot::inv.logit(posterior_linpred(class_stan_glm_mod6, newdata = viz_grid)) %>% 
              as.data.frame() %>% tibble::as_tibble() %>% 
              tibble::rowid_to_column("post_id") %>% 
              tidyr::gather(key = "pred_id", value = "value", -post_id) %>% 
              mutate_at(c("pred_id"), as.numeric) %>% 
              group_by(pred_id) %>% 
              summarise(trend_avg = mean(value),
                        trend_lwr = quantile(value, 0.05),
                        trend_upr = quantile(value, 0.95)) %>% 
              ungroup(),
            by = "pred_id") %>% 
  left_join(viz_grid %>% tibble::rowid_to_column("pred_id"),
            by = "pred_id") %>% 
  ggplot(mapping = aes(x = G)) +
  geom_ribbon(mapping = aes(ymin = y_lwr, ymax = y_upr,
                            group = Hue), 
              fill = "darkorange") +
  geom_ribbon(mapping = aes(ymin = trend_lwr, ymax = trend_upr,
                            group = Hue),
              fill = "grey") +
  geom_line(mapping = aes(y = trend_avg,
                          group = Hue),
            color = "black", size = 0.85) +
  facet_wrap(~Hue, labeller = "label_both", scales = 'free') +
  labs(y = "y") +
  theme_bw()
```

```{r}
posterior_predict(class_stan_glm_mod6, newdata = viz_grid) %>% 
  as.data.frame() %>% tibble::as_tibble() %>% 
  tibble::rowid_to_column("post_id") %>% 
  tidyr::gather(key = "pred_id", value = "value", -post_id) %>% 
  mutate_at(c("pred_id"), as.numeric) %>% 
  group_by(pred_id) %>% 
  summarise(num_post = n(),
            y_avg = mean(value),
            y_lwr = quantile(value, 0.05),
            y_upr = quantile(value, 0.95),
            prob_grt_0 = mean(value > 0)) %>% 
  ungroup() %>% 
  left_join(viz_grid %>% tibble::rowid_to_column("pred_id"),
            by = "pred_id") %>% 
  ggplot(mapping = aes(x = G, y = prob_grt_0)) +
  geom_line(mapping = aes(group = Hue,
                          color = as.factor(Hue)),
            size = 1.) +
  scale_fill_viridis_d("Hue") +
  scale_color_viridis_d("Hue") +
  labs(y = "Probability response is greater than 0") +
  theme_bw() +
  theme(legend.position = "top")
```



**Model 8**
```{r}
posterior_predict(class_stan_glm_mod8, newdata = viz_grid) %>% 
  as.data.frame() %>% tibble::as_tibble() %>% 
  tibble::rowid_to_column("post_id") %>% 
  pivot_longer(!c("post_id"), names_to = 'pred_id') %>% 
  mutate(across(.cols = 'pred_id', .fns = as.numeric)) %>% 
  group_by(pred_id) %>% 
  summarise(num_post = n(),
            y_avg = mean(value),
            y_lwr = quantile(value, 0.05),
            y_upr = quantile(value, 0.95)) %>% 
  ungroup() %>% 
  left_join(viz_grid %>% tibble::rowid_to_column("pred_id"),
            by = "pred_id") %>% 
  ggplot(mapping = aes(x = G)) +
  geom_ribbon(mapping = aes(ymin = y_lwr,
                            ymax = y_upr,
                            group = Hue,
                            fill = as.factor(Hue)),
              alpha = 0.5) +
  geom_line(mapping = aes(y = y_avg,
                          group = Hue,
                          color = as.factor(Hue)),
            size = 1.) +
  scale_fill_viridis_d("Hue") +
  scale_color_viridis_d("Hue") +
  facet_wrap(~Hue, scales = 'fixed')+
  labs(y = "y") +
  theme_bw() +
  theme(legend.position = "top")
```



```{r}
posterior_predict(class_stan_glm_mod8, newdata = viz_grid) %>% 
  as.data.frame() %>% tibble::as_tibble() %>% 
  tibble::rowid_to_column("post_id") %>% 
  tidyr::gather(key = "pred_id", value = "value", -post_id) %>% 
  mutate_at(c("pred_id"), as.numeric) %>% 
  group_by(pred_id) %>% 
  summarise(y_avg = mean(value),
            y_lwr = quantile(value, 0.05),
            y_upr = quantile(value, 0.95)) %>% 
  ungroup() %>% 
  left_join(boot::inv.logit(posterior_linpred(class_stan_glm_mod8, newdata = viz_grid)) %>% 
              as.data.frame() %>% tibble::as_tibble() %>% 
              tibble::rowid_to_column("post_id") %>% 
              tidyr::gather(key = "pred_id", value = "value", -post_id) %>% 
              mutate_at(c("pred_id"), as.numeric) %>% 
              group_by(pred_id) %>% 
              summarise(trend_avg = mean(value),
                        trend_lwr = quantile(value, 0.05),
                        trend_upr = quantile(value, 0.95)) %>% 
              ungroup(),
            by = "pred_id") %>% 
  left_join(viz_grid %>% tibble::rowid_to_column("pred_id"),
            by = "pred_id") %>% 
  ggplot(mapping = aes(x = G)) +
  geom_ribbon(mapping = aes(ymin = y_lwr, ymax = y_upr,
                            group = Hue), 
              fill = "darkorange") +
  geom_ribbon(mapping = aes(ymin = trend_lwr, ymax = trend_upr,
                            group = Hue),
              fill = "grey") +
  geom_line(mapping = aes(y = trend_avg,
                          group = Hue),
            color = "black", size = 0.85) +
  facet_wrap(~Hue, labeller = "label_both", scales = 'free') +
  labs(y = "y") +
  theme_bw()
```

```{r}
posterior_predict(class_stan_glm_mod8, newdata = viz_grid) %>% 
  as.data.frame() %>% tibble::as_tibble() %>% 
  tibble::rowid_to_column("post_id") %>% 
  tidyr::gather(key = "pred_id", value = "value", -post_id) %>% 
  mutate_at(c("pred_id"), as.numeric) %>% 
  group_by(pred_id) %>% 
  summarise(num_post = n(),
            y_avg = mean(value),
            y_lwr = quantile(value, 0.05),
            y_upr = quantile(value, 0.95),
            prob_grt_0 = mean(value > 0)) %>% 
  ungroup() %>% 
  left_join(viz_grid %>% tibble::rowid_to_column("pred_id"),
            by = "pred_id") %>% 
  ggplot(mapping = aes(x = G, y = prob_grt_0)) +
  geom_line(mapping = aes(group = Hue,
                          color = as.factor(Hue)),
            size = 1.) +
  scale_fill_viridis_d("Hue") +
  scale_color_viridis_d("Hue") +
  labs(y = "Probability response is greater than 0") +
  theme_bw() +
  theme(legend.position = "top")
```

The predictive trends of two models are consistent.



